"""added new column

Revision ID: ccbad5046bb3
Revises: 143d1c2e67b8
Create Date: 2024-02-02 01:03:30.700128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbad5046bb3'
down_revision = '143d1c2e67b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id_puppy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_puppy'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
